def update(benchmark, test, avoid_inner_order=True, **kwargs): ...
def compare(
    benchmark: dict,
    test: dict,
    key: str = None,
    avoid_inner_order: bool = False,
    **kwargs
): ...
def merge_dicts(orig_dict, new_dict): ...
def compare_with_reference(reference, original, updated, **kwargs): ...
